[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.filesystem = littlefs

lib_deps =
  jandrassy/EthernetENC
  bblanchon/ArduinoJson @ ^6.21.5

build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
